package quarantine

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/brightcolor/malwatch/internal/rootio"
	"github.com/brightcolor/malwatch/internal/safepath"
)

const entrySchema = 1

// payloadName is the archive file inside every entry directory.
const payloadName = "payload.tar.gz"

// newID names an entry after the moment it was made plus 8 random hex
// digits: the timestamp alone would collide whenever two files are
// quarantined in the same second, which a single infected upload with a
// handful of dropped shells does routinely.
func newID() (string, error) {
	var buf [4]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return "", err
	}
	return time.Now().UTC().Format("20060102T150405Z") + "-" + hex.EncodeToString(buf[:]), nil
}

// entryDir resolves id to its directory below storeRoot. id is generated by
// Store itself, but Get, Restore and Delete take it back from a caller - a
// path fragment slipped in as an id must not be able to name anything
// outside the store, the same reasoning InsideRoot applies to Restore's
// target.
func entryDir(storeRoot, id string) (string, error) {
	if id == "" || id == "." || id == ".." || filepath.Base(id) != id {
		return "", fmt.Errorf("ungültige Quarantäne-ID %q", id)
	}
	return filepath.Join(storeRoot, id), nil
}

// entryIDPattern is the shape newID produces: a UTC timestamp, a dash, and
// eight hex digits.
var entryIDPattern = regexp.MustCompile(`^\d{8}T\d{6}Z-[0-9a-f]{8}$`)

func isEntryID(name string) bool { return entryIDPattern.MatchString(name) }

// validRel refuses a relative path that does not name something inside the
// web root.
//
// An empty path and "." both resolve to the root itself: Store would then
// archive the whole website and delete it, which is not a thing any caller
// ever means to ask for. ".." and an absolute path leave the root outright.
// The callers are all ours, but "the caller is ours" is a property that stops
// holding the first time someone adds one.
func validRel(rel string) error {
	slashed := strings.ReplaceAll(rel, "\\", "/")
	clean := path.Clean("/" + slashed)
	if rel == "" || clean == "/" {
		return fmt.Errorf("leerer Pfad: die Quarantäne nimmt einzelne Dateien und Verzeichnisse, nicht den ganzen Webstamm")
	}
	if path.IsAbs(rel) || filepath.IsAbs(rel) {
		return fmt.Errorf("absoluter Pfad %q: erwartet wird ein Pfad unterhalb des Webstamms", rel)
	}
	// Die rohen Bestandteile, nicht die bereinigten: path.Clean rechnet ein
	// ".." gegen das Verzeichnis davor auf, also enthält das Ergebnis nie
	// eines, und eine Schleife darüber prüft nichts. Sie sah drei Fassungen
	// lang aus wie eine Prüfung. Ein "..", das im Ergebnis wieder aufgeht,
	// mag harmlos sein - der Pfad kommt aus einem Formularfeld, und ein
	// Aufrufer, der solche Pfade schickt, meint etwas anderes als das, was
	// hier ankommt.
	for _, part := range strings.Split(strings.Trim(slashed, "/"), "/") {
		if part == ".." {
			return fmt.Errorf("%q führt aus dem Webstamm heraus", rel)
		}
	}
	return nil
}

// StoreCopy is StoreCopyWith with the default reserve.
func StoreCopy(storeRoot string, src Source) (Entry, error) {
	return StoreCopyWith(storeRoot, src, DefaultSpace())
}

// StoreCopyWith archives src below storeRoot without touching src itself.
//
// Before the first byte it checks that the store's filesystem holds the
// archive, the copy unpacked to read it back and the reserve of space (see
// CheckStore); a *SpaceError leaves everything as it was.
//
// The archive is read back once, in full, before meta.json is written: a
// tar that looks written but does not actually unpack must not become the
// only copy of a file quarantine is about to vouch for. StoreWith builds on
// this and additionally removes the source; a repair running in overlay
// mode needs the copy on its own, with the source left alone.
func StoreCopyWith(storeRoot string, src Source, space Space) (Entry, error) {
	id, err := newID()
	if err != nil {
		return Entry{}, err
	}
	if err := validRel(src.RelPath); err != nil {
		return Entry{}, err
	}
	dir := filepath.Join(storeRoot, id)
	payload := filepath.Join(dir, payloadName)

	full := filepath.Join(src.Root, filepath.FromSlash(src.RelPath))
	info, err := os.Lstat(full)
	if err != nil {
		return Entry{}, err
	}
	kind := "file"
	if info.IsDir() {
		kind = "dir"
	}

	if err := CheckStore(storeRoot, []Source{src}, space); err != nil {
		return Entry{}, err
	}

	files, byteCount, err := writeArchive(payload, src.Root, src.RelPath)
	if err != nil {
		os.RemoveAll(dir)
		return Entry{}, err
	}

	verify := dir + ".verify"
	defer os.RemoveAll(verify)
	if err := readArchive(payload, verify); err != nil {
		os.RemoveAll(dir)
		return Entry{}, fmt.Errorf("quarantäne-archiv %s lässt sich nicht zurücklesen: %w", payload, err)
	}

	archiveInfo, err := os.Stat(payload)
	if err != nil {
		os.RemoveAll(dir)
		return Entry{}, err
	}

	entry := Entry{
		Schema:       entrySchema,
		ID:           id,
		CreatedAt:    time.Now().UTC().Format(time.RFC3339),
		Domain:       src.Domain,
		Root:         src.Root,
		RelPath:      src.RelPath,
		EntryKind:    kind,
		Origin:       src.Origin,
		Reason:       src.Reason,
		RuleID:       src.RuleID,
		Severity:     src.Severity,
		Files:        files,
		Bytes:        byteCount,
		ArchiveBytes: archiveInfo.Size(),
	}

	raw, err := json.MarshalIndent(entry, "", "  ")
	if err != nil {
		os.RemoveAll(dir)
		return Entry{}, err
	}
	// meta.json last: its presence is what makes an entry directory a
	// finished entry, both to List and to anyone reading the store by hand.
	if err := os.WriteFile(filepath.Join(dir, "meta.json"), raw, 0o640); err != nil {
		os.RemoveAll(dir)
		return Entry{}, err
	}

	return entry, nil
}

// Store is StoreWith with the default reserve.
func Store(storeRoot string, src Source) (Entry, error) {
	return StoreWith(storeRoot, src, DefaultSpace())
}

// StoreWith archives src and then removes it. Nothing is deleted until the
// archive above has been written, read back and given a meta.json - a run
// that dies before that point, or a store without the room for it, leaves the
// source exactly where it was.
func StoreWith(storeRoot string, src Source, space Space) (Entry, error) {
	entry, err := StoreCopyWith(storeRoot, src, space)
	if err != nil {
		return Entry{}, err
	}
	if err := removeBelow(src.Root, src.RelPath); err != nil {
		return Entry{}, err
	}
	return entry, nil
}

// removeBelow removes rel below root with everything in it, every step
// through an os.Root so a directory the website's user swaps for a symlink
// cannot send a root-run delete out of the tree (see rootio.RemoveAllIn).
func removeBelow(root, rel string) error {
	r, err := os.OpenRoot(root)
	if err != nil {
		return err
	}
	defer r.Close()
	if err := removeAllIn(r, filepath.FromSlash(rel)); err != nil {
		if rootio.EscapesRoot(err) {
			return fmt.Errorf("%s liegt hinter einem symbolischen Link, der aus %s herausführt, und bleibt stehen (%v). "+
				"Den Link prüfen und entfernen, danach den Auftrag erneut starten", rel, root, err)
		}
		return fmt.Errorf("%s lässt sich unter %s nicht entfernen: %w", rel, root, err)
	}
	return nil
}

// removeAllIn removes name below root with everything in it, through root.
func removeAllIn(root *os.Root, name string) error {
	return rootio.RemoveAllIn(root, name)
}

// readMeta reads one entry directory's meta.json.
func readMeta(dir string) (Entry, error) {
	raw, err := os.ReadFile(filepath.Join(dir, "meta.json"))
	if err != nil {
		return Entry{}, err
	}
	var entry Entry
	if err := json.Unmarshal(raw, &entry); err != nil {
		return Entry{}, err
	}
	return entry, nil
}

// List reads every entry in storeRoot, newest first, and names every
// directory it had to skip.
//
// A directory without a readable meta.json - an entry half-written when a run
// was interrupted, or the scratch directory StoreCopy verifies through - is
// skipped rather than failing the whole listing. The skipped names travel
// with the result because the caller that matters, the panel's index, deletes
// every row this listing does not name: a silently short list would take
// entries out of the index that are still very much on disk.
//
// Names and not just a count, because a directory that stays unreadable stops
// the index from ever tidying itself again, and nothing else in the tree ever
// says which one it is: no command lists it, the cron does not touch it, and
// Delete reaches it only with an id nobody knows. The name is the whole way
// back to it.
//
// A missing storeRoot is an error and not an empty store. The only caller
// passes a directory the installer creates; if it is gone, "there is nothing
// in quarantine" is the one answer that must not be given.
func List(storeRoot string) ([]Entry, []string, error) {
	dirEntries, err := os.ReadDir(storeRoot)
	if err != nil {
		return nil, nil, err
	}

	var skipped []string
	var entries []Entry
	for _, de := range dirEntries {
		if !de.IsDir() {
			continue
		}
		dir := filepath.Join(storeRoot, de.Name())

		// Scratch directories - <id>.verify while StoreCopy checks itself,
		// <id>.restore while Restore checks a payload before removing the
		// target - are not entries and are not damage either. They only look
		// like both, and one left behind by a killed process would otherwise
		// keep the panel's index from ever tidying itself again.
		//
		// Der Name allein entscheidet das aber nicht: ein Verzeichnis mit
		// einer meta.json ist ein Eintrag, wie immer es heißt. Nur am Muster
		// zu filtern hieße, dass eine spätere Änderung am Format der Kennung
		// jeden vorhandenen Eintrag lautlos aus der Liste nimmt - und weil
		// das Panel alles löscht, was die Liste nicht nennt, auch aus dem
		// Panel.
		if _, err := os.Stat(filepath.Join(dir, "meta.json")); err != nil {
			if !isEntryID(de.Name()) {
				continue // Arbeitsverzeichnis, kein halber Eintrag
			}
			skipped = append(skipped, de.Name())
			continue
		}

		entry, err := readMeta(dir)
		if err != nil {
			skipped = append(skipped, de.Name())
			continue
		}
		entries = append(entries, entry)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].ID > entries[j].ID })
	sort.Strings(skipped)
	return entries, skipped, nil
}

// Get reads one entry by id.
func Get(storeRoot, id string) (Entry, error) {
	dir, err := entryDir(storeRoot, id)
	if err != nil {
		return Entry{}, err
	}
	entry, err := readMeta(dir)
	if err != nil {
		return Entry{}, fmt.Errorf("quarantäne-eintrag %s nicht gefunden: %w", id, err)
	}
	return entry, nil
}

// Restore is RestoreWith with the default reserve.
func Restore(storeRoot, id string, force bool) error {
	return RestoreWith(storeRoot, id, force, DefaultSpace())
}

// RestoreWith puts an entry's content back at Root+RelPath.
//
// The target is checked with safepath.InsideRoot before anything is written:
// RelPath ultimately comes from a scan finding, and a symlink planted at
// that spot must not be able to steer the restore anywhere outside Root.
// Without force, an occupied target is left alone; with force, it is
// removed first so a directory-shaped entry cannot merge into whatever is
// already there.
//
// The payload is read to its end and the room measured before anything is
// written: the files at the target, with force also the scratch copy in the
// store, against the free space and the reserve. What --force removes counts
// as given back. An unreadable payload or a *SpaceError leaves the target and
// the entry as they were.
func RestoreWith(storeRoot, id string, force bool, space Space) error {
	entry, err := Get(storeRoot, id)
	if err != nil {
		return err
	}
	target := filepath.Join(entry.Root, filepath.FromSlash(entry.RelPath))
	if err := safepath.InsideRoot(entry.Root, target); err != nil {
		return err
	}

	_, statErr := os.Lstat(target)
	exists := statErr == nil
	if statErr != nil && !os.IsNotExist(statErr) {
		return statErr
	}

	payload := filepath.Join(storeRoot, id, payloadName)

	if exists && !force {
		return fmt.Errorf("%s ist bereits vorhanden; zum Überschreiben --force verwenden", target)
	}
	contents, err := payloadTally(payload)
	if err != nil {
		return fmt.Errorf("quarantäne-archiv %s ist unlesbar, %s bleibt unangetastet: %w", payload, target, err)
	}
	if err := checkRestore(storeRoot, entry, contents, exists, space); err != nil {
		return err
	}

	if exists {
		// The payload is unpacked into a scratch directory first, because
		// --force removes what is at the target. A payload that turns out to
		// be unreadable after the removal would leave the website with
		// neither the old directory nor the restored one - the one outcome
		// quarantine exists to make impossible.
		scratch := filepath.Join(storeRoot, id) + ".restore"
		defer os.RemoveAll(scratch)
		if err := readArchive(payload, scratch); err != nil {
			return fmt.Errorf("quarantäne-archiv %s ist unlesbar, %s bleibt unangetastet: %w",
				payload, target, err)
		}
		if err := removeBelow(entry.Root, entry.RelPath); err != nil {
			return err
		}
	}

	return readArchive(payload, entry.Root)
}

// Delete removes an entry's directory. An id that does not name a stored
// entry is an error: os.RemoveAll alone would succeed silently on a path
// that was never there, and that is not the same thing as having deleted it.
func Delete(storeRoot, id string) error {
	dir, err := entryDir(storeRoot, id)
	if err != nil {
		return err
	}
	if _, err := os.Stat(dir); err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("quarantäne-eintrag %s nicht gefunden", id)
		}
		return err
	}
	return os.RemoveAll(dir)
}
