package quarantine

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/brightcolor/malwatch/internal/safepath"
)

const entrySchema = 1

// payloadName is the archive file inside every entry directory.
const payloadName = "payload.tar.gz"

// newID names an entry after the moment it was made plus 8 random hex
// digits: the timestamp alone would collide whenever two files are
// quarantined in the same second, which a single infected upload with a
// handful of dropped shells does routinely.
func newID() (string, error) {
	var buf [4]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return "", err
	}
	return time.Now().UTC().Format("20060102T150405Z") + "-" + hex.EncodeToString(buf[:]), nil
}

// entryDir resolves id to its directory below storeRoot. id is generated by
// Store itself, but Get, Restore and Delete take it back from a caller - a
// path fragment slipped in as an id must not be able to name anything
// outside the store, the same reasoning InsideRoot applies to Restore's
// target.
func entryDir(storeRoot, id string) (string, error) {
	if id == "" || id == "." || id == ".." || filepath.Base(id) != id {
		return "", fmt.Errorf("ungültige Quarantäne-ID %q", id)
	}
	return filepath.Join(storeRoot, id), nil
}

// StoreCopy archives src below storeRoot without touching src itself.
//
// The archive is read back once, in full, before meta.json is written: a
// tar that looks written but does not actually unpack must not become the
// only copy of a file quarantine is about to vouch for. Store builds on
// this and additionally removes the source; a repair running in overlay
// mode needs the copy on its own, with the source left alone.
func StoreCopy(storeRoot string, src Source) (Entry, error) {
	id, err := newID()
	if err != nil {
		return Entry{}, err
	}
	dir := filepath.Join(storeRoot, id)
	payload := filepath.Join(dir, payloadName)

	full := filepath.Join(src.Root, filepath.FromSlash(src.RelPath))
	info, err := os.Lstat(full)
	if err != nil {
		return Entry{}, err
	}
	kind := "file"
	if info.IsDir() {
		kind = "dir"
	}

	files, byteCount, err := writeArchive(payload, src.Root, src.RelPath)
	if err != nil {
		os.RemoveAll(dir)
		return Entry{}, err
	}

	verify := dir + ".verify"
	defer os.RemoveAll(verify)
	if err := readArchive(payload, verify); err != nil {
		os.RemoveAll(dir)
		return Entry{}, fmt.Errorf("quarantäne-archiv %s lässt sich nicht zurücklesen: %w", payload, err)
	}

	archiveInfo, err := os.Stat(payload)
	if err != nil {
		os.RemoveAll(dir)
		return Entry{}, err
	}

	entry := Entry{
		Schema:       entrySchema,
		ID:           id,
		CreatedAt:    time.Now().UTC().Format(time.RFC3339),
		Domain:       src.Domain,
		Root:         src.Root,
		RelPath:      src.RelPath,
		EntryKind:    kind,
		Origin:       src.Origin,
		Reason:       src.Reason,
		RuleID:       src.RuleID,
		Severity:     src.Severity,
		Files:        files,
		Bytes:        byteCount,
		ArchiveBytes: archiveInfo.Size(),
	}

	raw, err := json.MarshalIndent(entry, "", "  ")
	if err != nil {
		os.RemoveAll(dir)
		return Entry{}, err
	}
	// meta.json last: its presence is what makes an entry directory a
	// finished entry, both to List and to anyone reading the store by hand.
	if err := os.WriteFile(filepath.Join(dir, "meta.json"), raw, 0o640); err != nil {
		os.RemoveAll(dir)
		return Entry{}, err
	}

	return entry, nil
}

// Store archives src and then removes it. Nothing is deleted until the
// archive above has been written, read back and given a meta.json - a run
// that dies before that point leaves the source exactly where it was.
func Store(storeRoot string, src Source) (Entry, error) {
	entry, err := StoreCopy(storeRoot, src)
	if err != nil {
		return Entry{}, err
	}
	full := filepath.Join(src.Root, filepath.FromSlash(src.RelPath))
	if err := os.RemoveAll(full); err != nil {
		return Entry{}, err
	}
	return entry, nil
}

// readMeta reads one entry directory's meta.json.
func readMeta(dir string) (Entry, error) {
	raw, err := os.ReadFile(filepath.Join(dir, "meta.json"))
	if err != nil {
		return Entry{}, err
	}
	var entry Entry
	if err := json.Unmarshal(raw, &entry); err != nil {
		return Entry{}, err
	}
	return entry, nil
}

// List reads every entry in storeRoot, newest first. A directory without a
// readable meta.json - an entry half-written when a run was interrupted, or
// the scratch directory StoreCopy verifies through - is skipped rather than
// failing the whole listing.
func List(storeRoot string) ([]Entry, error) {
	dirEntries, err := os.ReadDir(storeRoot)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var entries []Entry
	for _, de := range dirEntries {
		if !de.IsDir() {
			continue
		}
		entry, err := readMeta(filepath.Join(storeRoot, de.Name()))
		if err != nil {
			continue
		}
		entries = append(entries, entry)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].ID > entries[j].ID })
	return entries, nil
}

// Get reads one entry by id.
func Get(storeRoot, id string) (Entry, error) {
	dir, err := entryDir(storeRoot, id)
	if err != nil {
		return Entry{}, err
	}
	entry, err := readMeta(dir)
	if err != nil {
		return Entry{}, fmt.Errorf("quarantäne-eintrag %s nicht gefunden: %w", id, err)
	}
	return entry, nil
}

// Restore puts an entry's content back at Root+RelPath.
//
// The target is checked with safepath.InsideRoot before anything is written:
// RelPath ultimately comes from a scan finding, and a symlink planted at
// that spot must not be able to steer the restore anywhere outside Root.
// Without force, an occupied target is left alone; with force, it is
// removed first so a directory-shaped entry cannot merge into whatever is
// already there.
func Restore(storeRoot, id string, force bool) error {
	entry, err := Get(storeRoot, id)
	if err != nil {
		return err
	}
	target := filepath.Join(entry.Root, filepath.FromSlash(entry.RelPath))
	if err := safepath.InsideRoot(entry.Root, target); err != nil {
		return err
	}

	_, statErr := os.Lstat(target)
	exists := statErr == nil
	if statErr != nil && !os.IsNotExist(statErr) {
		return statErr
	}
	if exists {
		if !force {
			return fmt.Errorf("%s ist bereits vorhanden; zum Überschreiben --force verwenden", target)
		}
		if err := os.RemoveAll(target); err != nil {
			return err
		}
	}

	payload := filepath.Join(storeRoot, id, payloadName)
	return readArchive(payload, entry.Root)
}

// Delete removes an entry's directory. An id that does not name a stored
// entry is an error: os.RemoveAll alone would succeed silently on a path
// that was never there, and that is not the same thing as having deleted it.
func Delete(storeRoot, id string) error {
	dir, err := entryDir(storeRoot, id)
	if err != nil {
		return err
	}
	if _, err := os.Stat(dir); err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("quarantäne-eintrag %s nicht gefunden", id)
		}
		return err
	}
	return os.RemoveAll(dir)
}
