#!/usr/bin/php
<?php
/**
 * Fasst das Audit-Log zusammen: Treffer je Website und Regel.
 *
 *   waf-bericht [pfad-zum-audit-log]
 */
require '/usr/local/lib/waf/waf_audit.inc.php';

$datei = isset($argv[1]) ? $argv[1] : '/var/log/waf/audit.log';
if (!is_readable($datei)) {
	fwrite(STDERR, "Audit-Log nicht lesbar: $datei\n");
	exit(2);
}
$bericht = waf_audit_auswerten(file($datei, FILE_IGNORE_NEW_LINES));
if (empty($bericht)) {
	echo "Keine Treffer im Audit-Log.\n";
	exit(0);
}
printf("%-32s %-8s %-8s %-28s %s\n", 'Website', 'Regel', 'Treffer', 'Beispielpfad', 'Meldung');
foreach ($bericht as $zeile) {
	printf(
		"%-32s %-8s %-8d %-28s %s\n",
		$zeile['host'],
		$zeile['regel'],
		$zeile['treffer'],
		$zeile['beispiel'],
		$zeile['meldung']
	);
}
