package scanner

import (
	"path/filepath"
	"strings"
	"testing"
)

// awstatsPage is the shape of an AWStats 404 report: a generator line in the
// head, then a table of the URLs visitors asked for. On a public site that
// table is a list of the paths attackers probe, webshell names included.
const awstatsPage = `<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta name="generator" content="AWStats 7.8 (build 20200416) from config file awstats.example.conf (https://www.awstats.org)">
<title>Statistics for example</title>
</head>
<body>
<b>Advanced Web Statistics 7.8</b>
<table>
<tr><td>/wp-content/plugins/c99shell.php</td><td>404</td></tr>
<tr><td>/FilesMan.php</td><td>404</td></tr>
<tr><td>/b374k.php</td><td>404</td></tr>
</table>
</body></html>
`

func TestStatisticsReportsAreNotScanned(t *testing.T) {
	root := tree(t, map[string]string{
		"web/stats/awstats.example.errors404.html": awstatsPage,
	})

	rep := run(t, baseOptions(root))
	if len(rep.Findings) != 0 {
		t.Fatalf("a statistics report produced findings: %+v", rep.Findings)
	}
}

func TestTheSameNamesInAnOrdinaryPageAreStillFound(t *testing.T) {
	// The counter-check: without it the test above would also pass if the
	// rule had simply been deleted. The identical text without the generator
	// line must still be a finding.
	plain := strings.Replace(awstatsPage,
		`<meta name="generator" content="AWStats 7.8 (build 20200416) from config file awstats.example.conf (https://www.awstats.org)">`,
		"", 1)
	plain = strings.Replace(plain, "<b>Advanced Web Statistics 7.8</b>", "", 1)

	root := tree(t, map[string]string{"web/page.html": plain})

	rep := run(t, baseOptions(root))
	if len(rep.Findings) == 0 {
		t.Fatal("the webshell names were not found in an ordinary page")
	}
}

func TestAMarkerBelowTheHeaderDoesNotDisableTheScan(t *testing.T) {
	// An attacker who can write into a page must not be able to switch the
	// scanner off for it by pasting the word AWStats somewhere far down.
	var b strings.Builder
	b.WriteString("<html><body>\n")
	b.WriteString(strings.Repeat("<p>padding padding padding</p>\n", 400))
	b.WriteString("Advanced Web Statistics\n")
	b.WriteString("<?php eval($_POST['cmd']); ?>\n")
	b.WriteString("</body></html>\n")

	root := tree(t, map[string]string{"web/page.php": b.String()})

	rep := run(t, baseOptions(root))
	if len(rep.Findings) == 0 {
		t.Fatal("a marker outside the header disabled the scan for the file")
	}
}

func TestGeneratorMarkersOfEachTool(t *testing.T) {
	markers := []string{
		"Created by awstats",
		"Advanced Web Statistics",
		"Generated by Webalizer",
		"The Webalizer",
		"generated by GoAccess",
	}
	for _, marker := range markers {
		if !isGeneratedReport([]byte("<html><head>" + marker + "</head>")) {
			t.Errorf("marker %q was not recognised", marker)
		}
	}
	if isGeneratedReport([]byte("<html><head><title>A normal page</title></head>")) {
		t.Error("an ordinary page was taken for a statistics report")
	}
}

func TestReportDetectionUsesOnlyTheHead(t *testing.T) {
	head := []byte("<html><head>Created by awstats</head>")
	if !isGeneratedReport(head) {
		t.Fatal("marker in the head was not seen")
	}

	tail := append([]byte(strings.Repeat("x", reportHeader+10)), []byte("Created by awstats")...)
	if isGeneratedReport(tail) {
		t.Fatal("marker beyond the header was accepted")
	}
}

// goaccessFavicon is the base64 icon GoAccess embeds in the head of every
// report. It has been byte identical across the versions in use from 2022 to
// 2025. The generic ICO header at the front is followed by the GoAccess brand
// palette (…DGxsYAWFhYABwcHABfAP8A/9dfAADXrwAA…), which no other favicon
// carries, so a slice of it identifies a GoAccess report before the word
// "GoAccess" itself appears far down in the file.
const goaccessFavicon = `AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAADGxsYAWFhYABwcHABfAP8A/9dfAADXrwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIiIiIiIiIiIjMlUkQgAiIiIiIiIiIiIiIzJVJEIAAAIiIiIiIiIiIiMyVSRCAAIiIiIiIiIiIiIRERERERERERERERERERERIiIiIiIiIiIgACVVUiIiIiIiIiIiIiIiIAAlVVIiIiIiIiIiIiIiIhEREREREREREREREREREREAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`

// goaccessPage is the shape of a GoAccess HTML report: single-quoted meta
// tags, the embedded favicon, then far below a table of requested URLs. On a
// public site that table lists the paths attackers probe, and their base64
// payloads (here the encoded "eval(base64_dec") sit well past the 8 KB header
// window - just as the "generated by GoAccess" line does at byte ~97000. The
// scanner therefore has to recognise the page from its head, not its footer.
func goaccessPage() string {
	var b strings.Builder
	b.WriteString("<!DOCTYPE html><html lang='en'><head>")
	b.WriteString("<meta charset='UTF-8'>")
	b.WriteString("<meta name='referrer' content='no-referrer'>")
	b.WriteString("<meta http-equiv='X-UA-Compatible' content='IE=edge'>")
	b.WriteString("<meta name='google' content='notranslate'>")
	b.WriteString("<meta name='viewport' content='width=device-width, initial-scale=1'>")
	b.WriteString("<meta name='robots' content='noindex, nofollow'>")
	b.WriteString("<link rel='icon' href='data:image/x-icon;base64," + goaccessFavicon + "' type='image/x-icon' />")
	b.WriteString("<title>example.com</title>")
	b.WriteString("<style>.container{max-width:1200px}</style></head><body>")
	// The report embeds its templates and CSS first; the URL table and the
	// generator line come far below. Pad the body so the attack payload lands
	// well beyond the header window, the way it does in a real report.
	b.WriteString(strings.Repeat("<div class='wrap-general'>panel</div>", 400))
	b.WriteString("<script type='text/javascript'>var json_data={\"general\":{\"start_date\":\"26/Dec/2022\"},\"404\":{\"data\":[")
	b.WriteString("{\"method\":\"GET\",\"data\":\"/?q=ZXZhbChiYXNlNjRfZGVj\"}")
	b.WriteString("]}}</script>")
	b.WriteString("<footer>Dashboard - generated by GoAccess - goaccess.io</footer>")
	b.WriteString("</body></html>\n")
	return b.String()
}

func TestGoAccessReportsAreNotScanned(t *testing.T) {
	// The failing case: a GoAccess report lists a probed URL whose base64
	// payload trips php.obfuscation.base64_marker. The word "GoAccess" sits far
	// past the 8 KB header, so only the embedded favicon in the head can mark
	// the file as a report before it is scanned.
	page := goaccessPage()
	if strings.Index(page, "goaccess.io") < reportHeader {
		t.Fatalf("the generator line sits at byte %d, inside the header window - the fixture no longer reproduces the bug", strings.Index(page, "goaccess.io"))
	}

	root := tree(t, map[string]string{
		"web/stats/2022-12/goaindex.html": page,
	})

	rep := run(t, baseOptions(root))
	if len(rep.Findings) != 0 {
		t.Fatalf("a GoAccess report produced findings: %+v", rep.Findings)
	}
}

func TestGoAccessFaviconMarksAReportOnlyInTheHead(t *testing.T) {
	// The fix itself, without touching the disk: the embedded favicon marks a
	// GoAccess report, but only where a genuine report carries it - in the head.
	// The same bytes pasted below the header window must not count, or a late
	// paste would switch the scan off.
	head := []byte("<html><head><link rel='icon' href='data:image/x-icon;base64," + goaccessFavicon + "'></head>")
	if !isGeneratedReport(head) {
		t.Fatal("the GoAccess favicon in the head was not recognised")
	}

	tail := append([]byte(strings.Repeat("x", reportHeader+10)), []byte(goaccessFavicon)...)
	if isGeneratedReport(tail) {
		t.Fatal("the favicon beyond the header was accepted")
	}
}

func TestAGoAccessMarkerBelowTheHeaderDoesNotDisableTheScan(t *testing.T) {
	// The counter-check: recognising GoAccess must not mean searching the whole
	// file for the word. A page that carries "goaccess.io" and "generated by
	// GoAccess" far down - exactly where a real report has them - but no GoAccess
	// head must still be scanned. Widening the header window to reach that far
	// fails this.
	//
	// The payload is the encoded call that base64_marker catches, not an eval
	// shell: a local virus scanner quarantines the shell file before the test
	// can read it, while this string is scanned like any other content.
	var b strings.Builder
	b.WriteString("<?php\n")
	b.WriteString(strings.Repeat("// padding padding padding padding padding\n", 400))
	b.WriteString("$x = 'ZXZhbChiYXNlNjRfZGVj'; // encoded eval(base64_dec\n")
	b.WriteString("// generated by GoAccess - goaccess.io\n")
	b.WriteString("?>\n")
	if strings.Index(b.String(), "goaccess.io") < reportHeader {
		t.Fatalf("padding too short: the marker must sit beyond the %d byte header", reportHeader)
	}

	root := tree(t, map[string]string{"web/page.php": b.String()})

	rep := run(t, baseOptions(root))
	if len(rep.Findings) == 0 {
		t.Fatal("a late GoAccess marker disabled the scan for the file")
	}
}

func TestFindingsStillWorkNextToAReport(t *testing.T) {
	// A real shell in the same tree as a statistics report must still show up.
	root := tree(t, map[string]string{
		"web/stats/awstats.example.errors404.html": awstatsPage,
		"web/shell.php": "<?php @eval($_POST['cmd']);",
	})

	rep := run(t, baseOptions(root))
	if len(rep.Findings) != 1 {
		t.Fatalf("got %d findings, want exactly the planted shell: %+v", len(rep.Findings), rep.Findings)
	}
	if filepath.Base(rep.Findings[0].Path) != "shell.php" {
		t.Fatalf("the finding is in %s, want shell.php", rep.Findings[0].Path)
	}
}
