package scanner

import (
	"path/filepath"
	"strings"
	"testing"
)

// awstatsPage is the shape of an AWStats 404 report: a generator line in the
// head, then a table of the URLs visitors asked for. On a public site that
// table is a list of the paths attackers probe, webshell names included.
const awstatsPage = `<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta name="generator" content="AWStats 7.8 (build 20200416) from config file awstats.example.conf (https://www.awstats.org)">
<title>Statistics for example</title>
</head>
<body>
<b>Advanced Web Statistics 7.8</b>
<table>
<tr><td>/wp-content/plugins/c99shell.php</td><td>404</td></tr>
<tr><td>/FilesMan.php</td><td>404</td></tr>
<tr><td>/b374k.php</td><td>404</td></tr>
</table>
</body></html>
`

func TestStatisticsReportsAreNotScanned(t *testing.T) {
	root := tree(t, map[string]string{
		"web/stats/awstats.example.errors404.html": awstatsPage,
	})

	rep := run(t, baseOptions(root))
	if len(rep.Findings) != 0 {
		t.Fatalf("a statistics report produced findings: %+v", rep.Findings)
	}
}

func TestTheSameNamesInAnOrdinaryPageAreStillFound(t *testing.T) {
	// The counter-check: without it the test above would also pass if the
	// rule had simply been deleted. The identical text without the generator
	// line must still be a finding.
	plain := strings.Replace(awstatsPage,
		`<meta name="generator" content="AWStats 7.8 (build 20200416) from config file awstats.example.conf (https://www.awstats.org)">`,
		"", 1)
	plain = strings.Replace(plain, "<b>Advanced Web Statistics 7.8</b>", "", 1)

	root := tree(t, map[string]string{"web/page.html": plain})

	rep := run(t, baseOptions(root))
	if len(rep.Findings) == 0 {
		t.Fatal("the webshell names were not found in an ordinary page")
	}
}

func TestAMarkerBelowTheHeaderDoesNotDisableTheScan(t *testing.T) {
	// An attacker who can write into a page must not be able to switch the
	// scanner off for it by pasting the word AWStats somewhere far down.
	var b strings.Builder
	b.WriteString("<html><body>\n")
	b.WriteString(strings.Repeat("<p>padding padding padding</p>\n", 400))
	b.WriteString("Advanced Web Statistics\n")
	b.WriteString("<?php eval($_POST['cmd']); ?>\n")
	b.WriteString("</body></html>\n")

	root := tree(t, map[string]string{"web/page.php": b.String()})

	rep := run(t, baseOptions(root))
	if len(rep.Findings) == 0 {
		t.Fatal("a marker outside the header disabled the scan for the file")
	}
}

func TestGeneratorMarkersOfEachTool(t *testing.T) {
	markers := []string{
		"Created by awstats",
		"Advanced Web Statistics",
		"Generated by Webalizer",
		"The Webalizer",
		"generated by GoAccess",
	}
	for _, marker := range markers {
		if !isGeneratedReport([]byte("<html><head>" + marker + "</head>")) {
			t.Errorf("marker %q was not recognised", marker)
		}
	}
	if isGeneratedReport([]byte("<html><head><title>A normal page</title></head>")) {
		t.Error("an ordinary page was taken for a statistics report")
	}
}

func TestReportDetectionUsesOnlyTheHead(t *testing.T) {
	head := []byte("<html><head>Created by awstats</head>")
	if !isGeneratedReport(head) {
		t.Fatal("marker in the head was not seen")
	}

	tail := append([]byte(strings.Repeat("x", reportHeader+10)), []byte("Created by awstats")...)
	if isGeneratedReport(tail) {
		t.Fatal("marker beyond the header was accepted")
	}
}

func TestFindingsStillWorkNextToAReport(t *testing.T) {
	// A real shell in the same tree as a statistics report must still show up.
	root := tree(t, map[string]string{
		"web/stats/awstats.example.errors404.html": awstatsPage,
		"web/shell.php": "<?php @eval($_POST['cmd']);",
	})

	rep := run(t, baseOptions(root))
	if len(rep.Findings) != 1 {
		t.Fatalf("got %d findings, want exactly the planted shell: %+v", len(rep.Findings), rep.Findings)
	}
	if filepath.Base(rep.Findings[0].Path) != "shell.php" {
		t.Fatalf("the finding is in %s, want shell.php", rep.Findings[0].Path)
	}
}
