SecRuleEngine DetectionOnly
SecRequestBodyAccess On
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072
SecRequestBodyLimitAction ProcessPartial
SecResponseBodyAccess Off
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^$"
SecAuditLogParts ABCFHZ
SecAuditLogType Serial
SecAuditLog /var/log/waf/audit.log
SecAuditLogFormat JSON
SecAuditLogFileMode 0600
SecAuditLogDirMode 0750
SecTmpDir /var/cache/waf
SecDataDir /var/cache/waf
SecDebugLogLevel 0
SecStatusEngine Off
