Include /etc/nginx/modsecurity.conf
Include /etc/nginx/waf/einstellungen.conf
Include /etc/modsecurity/crs/crs-setup.conf
Include /etc/nginx/waf/crs-zusatz.conf
Include /etc/nginx/waf/ausnahmen-vorher.conf
Include /usr/share/modsecurity-crs/rules/*.conf
Include /etc/nginx/waf/ausnahmen-nachher.conf
Include /etc/nginx/waf/antwortrumpf.conf
Include /etc/nginx/waf/zustand.conf
